# Generated by Django 5.1.1 on 2024-10-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='full_name',
        ),
    ]
